# RENAME THE IMAGE TO image.jpg
# OPEN MATLAB AND RUN convert_jpg_to_coe.m
# RUN THIS MAKEFILE
# THE OUTPUT WILL BE IN THE FILE image_data.coe
# MOVE THE FILE TO /FPGA-Image-Processing/VGA-Image-Testing/VGA-Image-Testing.srcs/sources_1/new

rename:
	mv /Users/paulhondola/GitHub/FPGA-Image-Processing/COE-Convert/*.jpeg /Users/paulhondola/GitHub/FPGA-Image-Processing/COE-Convert/photo.jpg
move:
	cp image_data.coe /Users/paulhondola/GitHub/FPGA-Image-Processing/VGA-Image-Testing/VGA-Image-Testing.srcs/sources_1/new
