# RENAME THE IMAGE TO image.jpg
# OPEN MATLAB AND RUN convert_jpg_to_coe.m
# RUN THIS MAKEFILE
# THE OUTPUT WILL BE IN THE FILE image_data.coe

all:
	clang -Wall -o convert.exe coe_convert.c
	./convert.exe
